In [1]:
%load_ext autoreload
%autoreload 2

## Análisis de la información mutua entre las neuronas DV y LP

### 1. Estado de control

In [12]:
from DataManager import DataManager

control = DataManager(["LP","VD"], "TrozoC.txt")
control.describe()

,mean,std,min,max,median,mean_max,n_above_mean_max,n_at_or_below_mean_max
channel,,,,,,,,
LP,-2.492187e-08,0.082140,-0.710144,0.934448,0.000305,0.318146,157786,19642214
VD,4.385757e-02,0.032878,-2.170715,1.351624,0.043640,0.199236,159180,19640820

In [13]:
from DataWidget import crear_widget

crear_widget(control)

print("-")

VBox(children=(HBox(children=(Button(description='Inicio', style=ButtonStyle(), tooltip='Ir al inicio'), Butto…

-

In [17]:
counts_control, times_control = control.find_spikes()
print('Número de spikes de la neurona LP en estado de control:', counts_control["LP"])
print('Número de spikes de la neurona VD en estado de control:', counts_control["VD"])

Número de spikes de la neurona LP en estado de control: 31763
Número de spikes de la neurona VD en estado de control: 22275

In [18]:
size_window = control.optimal_window(counts_control, times_control)
size_window

{'LP': np.float64(14.349999999860268), 'VD': np.float64(12.849999999860273)}

### 2. Estado de inyección de Gaba

In [22]:
from DataManager import DataManager

gaba = DataManager(["LP","VD", "GABA"], "TrozoG.txt")
gaba.describe()

,mean,std,min,max,median,mean_max,n_above_mean_max,n_at_or_below_mean_max
channel,,,,,,,,
LP,-3.148344e-09,0.081101,-0.642090,0.926514,0.000000,0.300445,149786,16150214
VD,4.330858e-02,0.033377,-0.308838,0.552063,0.043030,0.212237,111629,16188371
GABA,1.361629e-01,0.284947,-0.054626,5.220642,0.119934,2.656277,52242,16247758

In [20]:
from DataWidget import crear_widget

crear_widget(gaba)

print("-")

VBox(children=(HBox(children=(Button(description='Inicio', style=ButtonStyle(), tooltip='Ir al inicio'), Butto…

-

In [23]:
counts_gaba, times_gaba = gaba.find_spikes()
print('Número de spikes de la neurona LP durante inyección de GABA:', counts_gaba["LP"])
print('Número de spikes de la neurona VD durante inyección de GABA:', counts_gaba["VD"])
print('Número de spikes de la neurona GABA durante inyección de GABA:', counts_gaba["GABA"])

Número de spikes de la neurona LP durante inyección de GABA: 27704
Número de spikes de la neurona VD durante inyección de GABA: 15560
Número de spikes de la neurona GABA durante inyección de GABA: 1306

In [24]:
size_window = gaba.optimal_window(counts_gaba, times_gaba)
size_window

{'LP': np.float64(14.000000000008699),
 'VD': np.float64(13.649999999988331),
 'GABA': np.float64(859.8000000000274)}

### 3. Estado de recuperación

In [25]:
from DataManager import DataManager

recuperacion = DataManager(["LP","VD"], "TrozoR.txt")
recuperacion

DataManager(filename='TrozoR.txt', channels=['LP', 'VD'], n_recordings=163, recording_length=100000)

In [26]:
from DataWidget import crear_widget

crear_widget(recuperacion)

print("-")

VBox(children=(HBox(children=(Button(description='Inicio', style=ButtonStyle(), tooltip='Ir al inicio'), Butto…

-

In [27]:
counts_recup, times_recup = recuperacion.find_spikes()
print('Número de spikes de la neurona LP en estado de recuperación:', counts_recup["LP"])
print('Número de spikes de la neurona VD en estado de recuperación:', counts_recup["VD"])

Número de spikes de la neurona LP en estado de recuperación: 25965
Número de spikes de la neurona VD en estado de recuperación: 18568

In [28]:
size_window = recuperacion.optimal_window(counts_recup, times_recup)
size_window

{'LP': np.float64(14.349999999982503), 'VD': np.float64(12.54999999997669)}

In [29]:
from EventExperiment import EventConfig, EventExperiment, SimpleEventConfig

# Empty thresholds use DataManager.global_mean_max; stride=1 and spike_detection are the defaults.
for word_length in [1,2,3,4,5,6,7,8]:
    test_config = EventConfig(
        word_length=word_length,
        simple_event=SimpleEventConfig(window=12.34, discretization="spike_detection"),
        notes= "Umbral = global_mean_max por canal"
    )
    test_experiment = EventExperiment(manager=test, config=test_config)

test_experiment.output_path

WindowsPath('c:/Users/Admin/Documents/CienciaDatos/Teoría de la Información/practicas_TI/DatosSinapsisArtificial-TI/experiments/TrozoC_window-12.34_word-8.json')